### ISSUE TITLE
Weapon Names

### ISSUE THREAD

**Issue by MiddleSkillz** [Dev-CasperTheGhost/snaily-cadv2#10]
**Describe the feature you'd like**
I think it would be nice to include all the stock GTA weapons by default like vehicles, of course leaving out the laser weapons and such.

**Comment by casperiv0** [comment]
Yeah such feature could be added easily! I might have some time for that tomorrow.

**Comment by casperiv0** [comment]
Most likely will be added in 1.4.0 (now 1.3.4), Thanks for the suggestion!
