### ISSUE TITLE
Database Connection Error

### ISSUE THREAD

**Issue by andrewconleyaziti** [Dev-CasperTheGhost/snaily-cadv2#11]
After a few hours of my server running using `npm start`, I get this error:
[https://i.gyazo.com/7b5c2ac8fbc56017f9ac309b628764cd.png](https://i.gyazo.com/7b5c2ac8fbc56017f9ac309b628764cd.png)

I've tried looking at the DB service status, which says it is running and when I try connecting to it in the CLI, it works fine. I don't know why it suddenly loses connection after a few hours of running.

**Comment by casperiv0** [comment]
I think it's because it's idling, Another community had this issue but they were able to connect to the CAD with no issue. 

Thanks for reporting this though!
