### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by andrewconleyaziti** [Dev-CasperTheGhost/snaily-cadv2#12]
**Describe the feature you'd like**
Some CAD systems (in real life and FiveM) have sounds when a dispatcher assigns you a call so that you know they've placed you on a call. Also having a priority tone and something similar in the CAD would be nice as well.

**Comment by casperiv0** [comment]
I'm working on a no-reload function so the page doesn't reload everytime you add/change something, after that I'll be working on sounds and more.

Thanks for the suggestion.
