### ISSUE TITLE
React Redux Error?

### ISSUE THREAD

**Issue by andrewconleyaziti** [Dev-CasperTheGhost/snaily-cadv2#13]
**Describe the bug**
When I pulled v1.5.0 and installed react-redux per the README and CHANGELOG, and run `npm run build` it comes up with the following error: https://i.gyazo.com/8642bd834885802fd76b06600c6133f6.png

When I ran `yarn add redux react-redux react-thunk` to install Redux, it came up with these missing peer dependencies:
https://i.gyazo.com/0c9540a2e15fab1f6fbcc2d755c5d99a.png

**Comment by casperiv0** [comment]
Hey!

Those are only warnings so you ignore those. So you should be able start the CAD with no problem

Thanks Casper

**Comment by andrewconleyaziti** [comment]
Okay. I did have a bug where when I updated the officer status, the dispatch panel wouldn't update without me having to manually reload the page. Also 911 calls wouldn't show up at all.

Sent from my Samsung Galaxy Note 9

________________________________

**Comment by casperiv0** [comment]
Officer status updates are coming in the next update, might be today or tomorrow, I'll see for the 911 calls too.

**Comment by casperiv0** [comment]
Just pushed the update for the officer status, 911 calls seem to work fine, I'll check again in my demo.

**Comment by casperiv0** [comment]
Everything seems to work fine. Let me know if there's any other issues! 

Thank you.
