### ISSUE TITLE
Adding a Weapon

### ISSUE THREAD

**Issue by andrewconleyaziti** [Dev-CasperTheGhost/snaily-cadv2#14]
**Describe the bug**
When I try to add a weapon into the CAD (Admin panel) it doesn't add the weapon. In the CLI, it comes up with the following error: https://i.gyazo.com/ee764704837f9e9e154023fdee500f68.png
https://i.gyazo.com/37511346ddab5d90fb881961eec95c4a.png

**Comment by casperiv0** [comment]
Hello!

Just pushed an update! Should be fixed now.

Thanks for reporting.

**Comment by andrewconleyaziti** [comment]
Thank you!
