### ISSUE TITLE
i got it working but can only use it in my vps and have pf it and cant register users outside 

### ISSUE THREAD

**Issue by arcadejackpotmaster** [Dev-CasperTheGhost/snaily-cadv2#18]
infinite loading when I try to make a user outside my vps

**Comment by arcadejackpotmaster** [comment]
![Create An Account - Google Chrome 7_9_2020 8_52_18 PM](https://user-images.githubusercontent.com/47673794/87114753-39a6cd00-c226-11ea-800c-0f9ddcf86486.png)

**Comment by casperiv0** [comment]
Hey,

Change the localhost in the client config and package.json(client folder ) to the ip of your Vps

**Comment by arcadejackpotmaster** [comment]
config.js in the main file

**Comment by casperiv0** [comment]
No, `./client/src/config/config.js` and `./client/package.json` It is located in those files

**Comment by arcadejackpotmaster** [comment]
]
![Please Login - Google Chrome 7_9_2020 10_16_07 PM](https://user-images.githubusercontent.com/47673794/87119086-d6bb3300-c231-11ea-8c2d-1db25be311b0.png)
it still haveing the same infinite loading issue

**Comment by casperiv0** [comment]
Run `yarn build` in the client folder after changing

**Comment by arcadejackpotmaster** [comment]
ok did it is working thanks just wondering do you suggest using redirects to put it on a domain or can i set the URL as the proxy?

**Comment by casperiv0** [comment]
you can point the IP to a domain yes, It might not work depending on how you/provider has it setup though.

**Comment by arcadejackpotmaster** [comment]
Thanks you are now welcome to close this and thanks again for the help.

**Comment by casperiv0** [comment]
Sure, no problem! Enjoy.
