### ISSUE TITLE
I have a problem with installing the cad

### ISSUE THREAD

**Issue by ghost** [Dev-CasperTheGhost/snaily-cadv2#2]
https://prnt.sc/sr0qlf

Can someone help me?

**Comment by casperiv0** [comment]
Hello, make sure you have the latest version of yarn installed.
https://classic.yarnpkg.com/en/docs/install/#windows-stable

**Comment by ghost** [comment]
Is it possible to run it on linux?

**Comment by casperiv0** [comment]
Yes, you should be able to. You are able to select which version of linux here: https://classic.yarnpkg.com/en/docs/install/

**Comment by ghost** [comment]
Now there's another error
https://prnt.sc/sr0z4o

**Comment by casperiv0** [comment]
That might've been on my end, Run `npm install --save-dev nodemon`

**Comment by ghost** [comment]
Now the server starts, but there is an error when calling the page
https://prnt.sc/sr137d

Sorry for all those messages :D

**Comment by casperiv0** [comment]
It's okay! You don't have to go to :3001, you can just go to http://localhost/

**Comment by ghost** [comment]
Then Im landing on the default apache2 page

**Comment by casperiv0** [comment]
Ah, make sure to stop Apache2, you only need MySQL.
If you're running another process with Apache2 you can go into `./client/package.json` and look for `serve` in `scripts` and change the `-l 80` to `-l 81` to run it on port `81`

**Comment by ghost** [comment]
Nice :D Now, when I try to register, the create account button is just loading...
https://prnt.sc/sr1a3k

**Comment by casperiv0** [comment]
This might be because of your proxy settings, Can you check the console if there's any proxy errors?

**Comment by ghost** [comment]
I think there is an error with the database
https://prnt.sc/sr1gij

**Comment by ghost** [comment]
Is it possible to change the auth mode?

**Comment by ghost** [comment]
Fixed this with changing the database user... But the button is still loading...

**Comment by casperiv0** [comment]
Okay, make sure you the `backendURL` is correct in `./client/src/config/config.js`, This has to be set to your VPS IP-address and port, so like: `http://1.1.1.1:3001`

**Comment by casperiv0** [comment]
And if you change it make sure to also run `npm run build` in `./client` to make sure it all has been saved.

**Comment by ghost** [comment]
Nothing changed... :C

**Comment by ghost** [comment]
https://prnt.sc/sr1lfr
Does this help?

**Comment by ghost** [comment]
Do I have to change the URL in package.json too?

**Comment by casperiv0** [comment]
Can you check the console for any errors, i'm sorry for all the inconvenience.

**Comment by ghost** [comment]
No error in the console... Np

**Comment by casperiv0** [comment]
OH WAIT, I see it, the port is after a `/` it has to be infront of that.

**Comment by casperiv0** [comment]
Try `http://91.218.67.47:3001/`

**Comment by casperiv0** [comment]
And than also run `npm run build` in `./client`, That should fix it.

**Comment by ghost** [comment]
I'll do. Give me a second :D

**Comment by ghost** [comment]
Now we got this
https://prnt.sc/sr1orh

**Comment by casperiv0** [comment]
That's a problem on my end, I'll quickly push a fix for it.

**Comment by ghost** [comment]
thanks :D

**Comment by casperiv0** [comment]
Alright pushed the update, make sure to run `git pull origin master` from the root folder and then run the following:

`cd client`
`npm run build`
`cd ../`
`npm start`

**Comment by ghost** [comment]
Did everything as you said now there is this message coming up
https://prnt.sc/sr1szm

**Comment by casperiv0** [comment]
Don't mind that error for now. The CAD should run fine.

**Comment by ghost** [comment]
The error with the dispatch_status is still coming up

**Comment by ghost** [comment]
Should I try to reinstall?

**Comment by casperiv0** [comment]
hmm, Its really weird because for me I don't get any of those errors. It might be because you're on linux, if you want i could try to set it up for you, only if you allow me obviously.

**Comment by casperiv0** [comment]
I'd say try to reinstall and if that wouldn't work try updating your database too

**Comment by ghost** [comment]
After reinstalling the cad works :D

**Comment by casperiv0** [comment]
Cool, Hope you enjoy! Again sorry for all the inconvenience.

**Comment by ghost** [comment]
No problem..
thanks for your help
