### ISSUE TITLE
Borken proxy

### ISSUE THREAD

**Issue by arcadejackpotmaster** [Dev-CasperTheGhost/snaily-cadv2#20]
hello, I set the proxy and everything up correctly to my website but for whatever reason it broke and is know to go exclusively to the ip of my VPS when it is set to point to the website.

**Comment by casperiv0** [comment]
Hey, 

This is not really an issue with the CAD, i suggest you google how to setup a domain name with an ip and setup the proxy.

Ps: if you change anything in the config file, you will need to run the build command again.
