### ISSUE TITLE
"Keep me logged in"

### ISSUE THREAD

**Issue by JemmaSinclair** [Dev-CasperTheGhost/snaily-cadv2#21]
It would be nice to see a button on the login screen to keep the IP logged in until the password changes, that way if someone has to log in after their chrome data is reset.

**Comment by casperiv0** [comment]
Hey, this could be a cool feature, but im saving the cookie in the browser, i can do so the cookie doesn't expire. It will only expire if someone deletes cookie data.

I Will write this down and close the issue.

Thanks for suggesting!
