### ISSUE TITLE
Civ Panel not showing 2/4 license statuses

### ISSUE THREAD

**Issue by JemmaSinclair** [Dev-CasperTheGhost/snaily-cadv2#22]
**Describe the bug**
In civilian area, while reviewing a character, it does not show the status of the Firearms License or the Pilots Licence.
**To Reproduce**
Create Character 
Give any form of license to all four
Only ones that will show up will be DL and CCW

**Expected behavior**
showing the status

**Screenshots**
![image](https://user-images.githubusercontent.com/61020381/87366532-eba40900-c546-11ea-82ea-9c1f66766bb7.png)
![image](https://user-images.githubusercontent.com/61020381/87366543-f2cb1700-c546-11ea-98a6-ac1d19be6424.png)

**Comment by casperiv0** [comment]
Not sure why this is happening, try to edit the licenses and see if they popup again

**Comment by casperiv0** [comment]
I have found the issue, I'm currently not home for ~7days, once home I'll be able to fix it.

**Comment by casperiv0** [comment]
Bug has been fixed.
