### ISSUE TITLE
Error: Cannot GET /

### ISSUE THREAD

**Issue by DiabolicAngeL** [Dev-CasperTheGhost/snaily-cadv2#23]
Hello, I am trying to install it on linux (CentOS), I am probably doing many things wrong, my first time installing something like this.
Is there any tutorial to install this on linux or it should be the same?

Thanks!

**Comment by casperiv0** [comment]
It should be the same, make sure to follow along with the [installation instructions](https://github.com/Dev-CasperTheGhost/snaily-cadv2#installation), once the CAD is running, goto: http://localhost/ (not http://localhost:port/ (so without the port))

**Comment by DiabolicAngeL** [comment]
> It should be the same, make sure to follow along with the [installation instructions](https://github.com/Dev-CasperTheGhost/snaily-cadv2#installation), once the CAD is running, goto: http://localhost/ (not http://localhost:port/ (so without the port))

I'll try again and I'll reply with results. Thanks!

@Dev-CasperTheGhost Ps. On step 6 I run `npm install` in `client/src/config/` location as step 5 says about the config or in `snaily-cadv2` folder? Or it doesn't mater?

**Comment by casperiv0** [comment]
No, you need to run `npm install` in the `client` folder. (not /client/src/config)

**Comment by DiabolicAngeL** [comment]
@Dev-CasperTheGhost my problem was that I didn't see I'm not using npm start as root.

Another problem is that, it doesn't read the url I put in `/snaily-cadv2/client/src/config/config.js`
I can't open the panel using domain.com:port (Except if it doesn't work like this)

And also it is using different port after every restart.
For example it started with port `38450` after restart it used port `38472` etc etc

**Comment by casperiv0** [comment]
You can change the port for client in `client/package.json` at `scripts`: `serve`, change the `-l 80` to `-l a_port`, make sure to run `npm run build` in the client folder after changing the `config` and `package.json`

**Comment by DiabolicAngeL** [comment]
I can open the page only from ip not from domain and alsom i can't register it stucks at loading

![image](https://user-images.githubusercontent.com/68332732/87851862-f969dd80-c8fc-11ea-9460-8fa4d9fed3bb.png)

Any ideas?

**Comment by casperiv0** [comment]
Might be something wrong in the proxy for the domain, make sure you also changed the `proxy` in `client/package.json` from `http://localhost:3001` to `http://your_ip:port`

**Comment by DiabolicAngeL** [comment]
Thanks a lot for the help!

Sometimes it was working sometimes not, but finally I think I understood how it works.

Just asking to be 100% sure.
the port in `scripts`:`serve` has to be different than all the rest. All the rest have to be the same, am I correct?

And one more newbie question, what should I put here `Update AOP`? x)

**Comment by casperiv0** [comment]
That's correct, Update AOP is where you can update the area of roleplay

**Comment by DiabolicAngeL** [comment]
> That's correct, Update AOP is where you can update the area of roleplay

Perfect, thank you very much for your help and your patience! You did a FANTASTIC job with the cad.

**Comment by casperiv0** [comment]
Glad I could help. Thanks!

closing this issue, if you have any other issue, feel free to open a new one.

**Comment by DiabolicAngeL** [comment]
@Dev-CasperTheGhost , I reply here to not open a new issue just for this.

Do you know how I can start the cad on boot in linux?
I found something about pm2 but I don't know how to start it with that. They are talking about the server.js but which one is it? :P

Example `pm2 start server.js`

**Comment by casperiv0** [comment]
Yeah, pm2 is a great choice for that.

First: `npm install -g pm2`

In server folder: `pm2 start server.js --name cad-server`
In client folder: `pm2 start npm --name cad-client -- run serve`

then run `pm2 startup` that should do the trick

**Comment by DiabolicAngeL** [comment]
> Yeah, pm2 is a great choice for that.
> 
> First: `npm install -g pm2`
> 
> In server folder: `pm2 start server.js --name cad-server`
> In client folder: `pm2 start npm --name cad-client -- run serve`
> 
> then run `pm2 startup` that should do the trick

I love you! Thanks a lot!

**Comment by casperiv0** [comment]
No problem!
