### ISSUE TITLE
Custom Menus

### ISSUE THREAD

**Issue by DiabolicAngeL** [Dev-CasperTheGhost/snaily-cadv2#24]
**Describe the feature you'd like**
It will be very cool and helpful to be able to add custom items to the main menu from the admin section. 
For example to be able to add our website or a live map etc. 
And if possible to be able to add custom links to the profile menu too.

![image](https://user-images.githubusercontent.com/68332732/87888190-962a9900-ca2b-11ea-9942-143440dbcd86.png)

`PS. The game resources for calling doesn't work? Or I'm doing something wrong?`

**Comment by casperiv0** [comment]
Yeah I could make that work, I'm currently working on other features at the moment so it might come later.

Can you send me a screenshot of your server (server.lua) file? Maybe I can see if there's something wrong in the URL/code

**Comment by DiabolicAngeL** [comment]
@Dev-CasperTheGhost Perfect, take your time x)

Here are my server.lua for both resources.
The tow resource is giving an error when I restart from the game.

Here is the error:

```
MainThrd/ Error loading script client.lua in resource snailyCAD-towservice: @snailyCAD-towservice/client.lua:6: attempt to call a nil value (global 'TriggerClientEvent')
[    409563] [    GTAProcess]             MainThrd/ stack traceback:
[    409563] [    GTAProcess]             MainThrd/ 	@snailyCAD-towservice/client.lua:6: in main chunk
[    409578] [    GTAProcess]             MainThrd/ Failed to load script client.lua.

```

**snailyCAD-911service - server.lua**

```
-- CONFIG
-------------------------------------------
--- Url to the "server" of the CAD, default port is 3001
local URL_TO_CAD = 'http://server-ip-here' -- No slash at the end 
local PORT = "proxy-port"
-------------------------------------------

-- CODE 
-------------------------------------------

-- Register chatmessage
RegisterServerEvent("chatMessage")

RegisterCommand("call911", function(source, args)
    CancelEvent()
    local name = GetPlayerName(source)
    local description = args
    TriggerClientEvent("911Call", source, name, description)
end)

-- register the updater
RegisterServerEvent("911CallUpdate")

-- POST the call to the CAD
AddEventHandler("911CallUpdate", function(street, name, description)
    PerformHttpRequest(URL_TO_CAD .. ":" .. PORT .. '/global/create-911-call',
                       function(err, text, headers) end, 'POST',
                       json.encode({name = name, location = street, description = table.concat(description, ' ')}),
                       {["Content-Type"] = 'application/json'})

    CancelEvent()
end)

-- CODE
-------------------------------------------
```


**snailyCAD-towservice - server.lua**
```
-- CONFIG
-------------------------------------------
--- Url to the "server" of the CAD, default port is 3001
local URL_TO_CAD = 'http://server-ip-here' -- No slash at the end 
local PORT = "proxy-port"
-------------------------------------------

-- CODE 
-------------------------------------------

-- Register chatmessage
RegisterServerEvent("chatMessage")

RegisterCommand("calltow", function(source, args)
    CancelEvent()
    local name = GetPlayerName(source)
    local description = args
    TriggerClientEvent("towCall", source, name, description)
end)

-- register the updater
RegisterServerEvent("towCallUpdate")

-- POST the call to the CAD
AddEventHandler("towCallUpdate", function(street, name, description)
    PerformHttpRequest(URL_TO_CAD .. ":" .. PORT .. '/global/create-tow-call',
                       function(err, text, headers) end, 'POST', json.encode(
                           {
            caller = name,
            location = street,
            description = table.concat(description, ' ')
        }), {["Content-Type"] = 'application/json'})

    CancelEvent()
end)

-- CODE
-------------------------------------------

```

**Comment by casperiv0** [comment]
You have to change the `URL_TO_CAD` and `PORT` to your configuration, that's most likely why there's an error

**Comment by DiabolicAngeL** [comment]
I changed them, on the url I tried with a domain that points to the server ip and also I tried with the server's IP and the port.

How I have it

I changed all the `3001` ports to *example_port* `30265`
I changed `80` port to *example_port* `30845`
So I have: `config.js, client/src/config/config.js` the port `30265`
In packages.json I use proxy port `10265` and `scripts:serve` the port `30845`

The panel is opening at port http://123.456.789:30845 / http://domain.com:30845

In game resources I used

```
local URL_TO_CAD = 'http://123.456.789' -- No slash at the end 
local PORT = "30265" tried with `30845` too and it doesn't work.
```

I think I'll try to reinstall it and see how it goes.

=====

Edit: @Dev-CasperTheGhost I tried again with clean installation, I left port 3001 unchanged and I just changed the port 80. I type /call911 or /calltow and I do not see anything in CAD. Also the panic button doesn't seem to do anything.

What i noticed is that when i visit http://server-ip:3001 it shows `Cannot GET /`
May that be a problem and if yes how do I fix that?

Thanks a lot!

**Comment by casperiv0** [comment]
The `Cannot GET /` is not a problem at all, Not sure why this is happening though. Do you have any errors in the fivem server console (not F8, the console where the server was started in), or in the console of the CAD?

**Comment by DiabolicAngeL** [comment]
> The `Cannot GET /` is not a problem at all, Not sure why this is happening though. Do you have any errors in the fivem server console (not F8, the console where the server was started in), or in the console of the CAD?

I do not see any errors in game's console at all.
How can i see the cad error logs or open the console while use pm2?
PS. When I started it without it the first time, it started without any errors

**Comment by casperiv0** [comment]
You can use `pm2 logs` to see all the logs (can be a little overwhelming)

**Comment by DiabolicAngeL** [comment]
> You can use `pm2 logs` to see all the logs (can be a little overwhelming)

No errors at all
```
$ pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/home/username/.pm2/logs/cad-server-error.log last 15 lines:
/home/username/.pm2/logs/cad-client-error.log last 15 lines:
/home/username/.pm2/logs/cad-server-out.log last 15 lines:
0|cad-serv | Connected to Database
0|cad-serv |
0|cad-serv | You're all up to date.

/home/username/.pm2/logs/cad-client-out.log last 15 lines:
1|cad-clie |
1|cad-clie | > client@0.1.0 serve /home/username/cad/client
1|cad-clie | > serve -s build -l port-here
1|cad-clie |
1|cad-clie | INFO: Accepting connections at http://localhost:port-here
```

It says Accepting connections at http://**localhost**:port-here even if I changed `localhost` with my server's IP

But I do not thing that's a problem?

**Comment by casperiv0** [comment]
That will always show `localhost`, but I see you have `port-here` not sure if that's just for showing me, if not I suggest you to change that. I'll check on my dev server later to see If it's a problem with the script.

PS: After you edit `client/src/config/config.js` make sure to always run `yarn build` in `client/` to update the config

**Comment by DiabolicAngeL** [comment]
> That will always show `localhost`, but I see you have `port-here` not sure if that's just for showing me, if not I suggest you to change that. I'll check on my dev server later to see If it's a problem with the script.
> 
> PS: After you edit `client/src/config/config.js` make sure to always run `yarn build` in `client/` to update the config



Yes the `port-here` was just to show you.
I also do the `yarn build ` in `client` after every changes (Just to be sure). You taught me well x)
I wrote down everything you told me and I follow it step by step! I probably miss something stupid or maybe something else is wrong. I have no idea

Thank you very very much!

**Comment by casperiv0** [comment]
The port in your server.lua, that is for the `cad-server` right? If not change it to that to the port you have set the for `cad-server`

Oh and make sure that you have text after the `/call911` E.G. `/call911 I need help`, I'll most likely change that so it's no required

**Comment by DiabolicAngeL** [comment]
The port in server lua I tried with the default `3001` *(I didn't change it after I reinstall it)* and it didn't work, after I said I'll try with the panel's port `80` *( I changed it so I used the one I choose)* and it didn't work with that too.

I tried `/call911` with and without text after but I can't make it work. Should I do any specific changes inside the cad for it to work or something else? It's a bit weird that the cad works fine but it looks like it doesn't connect with the server.

May be something very small and stupid and because I'm confused with all those stuff maybe I missed it and I wasted your time too. And also I'll bang my head to the wall. ^^

Thanks again for the help and your patience!

**Comment by casperiv0** [comment]
It seems to all work for me, I think you just have something wrong in the port setup, make sure that 

In `config.js`(main folder) and the port in `server.lua` are both the same, that should work, if it wouldn't work after, make sure you have the ports open that you have set.

**Comment by DiabolicAngeL** [comment]
Hello, the ports are open, check below all my configs

![image](https://user-images.githubusercontent.com/68332732/88069555-e6ac0e80-cb71-11ea-972b-fa04e12b0439.png)

### **Main config.js:** 
![image](https://user-images.githubusercontent.com/68332732/88069635-05120a00-cb72-11ea-8a36-875829daf0f1.png)
---
### **packages.json**
![image](https://user-images.githubusercontent.com/68332732/88069818-42769780-cb72-11ea-9254-dba998589573.png)
---
### **client/src/config/config.js**
![image](https://user-images.githubusercontent.com/68332732/88069933-633eed00-cb72-11ea-9ee0-e51e0fe8688f.png)
---
### **server.lua**
![image](https://user-images.githubusercontent.com/68332732/88070236-c2046680-cb72-11ea-9bf2-46c0321e32c3.png)


---
Also I think this is wrong here? :P 
![image](https://user-images.githubusercontent.com/68332732/88070824-68506c00-cb73-11ea-9274-abf80e8fa905.png)

**Comment by casperiv0** [comment]
I uploaded that version earlier today, you can update yea.

**Comment by casperiv0** [comment]
Aahhhh! I see the problem, can you download the updated version for the CAD resources? Then check if its still broken, ifso Ill check tomorrow since Ive got a busy evening lol

**Comment by DiabolicAngeL** [comment]
It says that my version is 1.5.8 and the updated is 1.5.7, I updated and it is showing that
You mean the cad resources from here `client/build/downloads`? I did that too :P

It's ok take your time and have a nice day!

**Comment by casperiv0** [comment]
I updated the downloads, re-download them [here](https://github.com/Dev-CasperTheGhost/snaily-cadv2/tree/master/client/public/downloads)

**Comment by DiabolicAngeL** [comment]
@Dev-CasperTheGhost It finally works!!! Thank you very very much!

I also fixed the `snailyCAD-towservice`, I had this error and it wasn't working at all:

![image](https://user-images.githubusercontent.com/68332732/88187436-ceea8e00-cc36-11ea-9641-7135b5a31c6c.png)

**I replaced this *(tow client.lua)*** `TriggerClientEvent('chat:addSuggestion', '/calltow', 'Call the tow truck services')`

**With this *(From the 911 resource client.lua)*** and now tow works too!
`-- TriggerEvent('chat:addSuggestion', '/calltow', 'Call the tow truck services', {})`

---
Ps. Is the panic button doing something in-game or in the cad?
I press it, it says `DIABOLICANGEL STARTED PANIC BUTTON` but I do not see anything, or a sound or something.

**Some more suggestions**

- Will be cool to have a sound notification about calls etc
- Will be helpful to show coordinates on 911/tow calls after location name

**Comment by casperiv0** [comment]
I'll add that fix in the next update, thankyou.

The panic button shows a message in the CAD to all connected clients who are on the dispatch/leo page, you should already hear a sound when a new sound is coming in, if you don't hear it make sure you allow sound from your domain

**Comment by DiabolicAngeL** [comment]
> I'll add that fix in the next update, thankyou.
> 
> The panic button shows a message in the CAD to all connected clients who are on the dispatch/leo page, you should already hear a sound when a new sound is coming in, if you don't hear it make sure you allow sound from your domain

The sound is enabled but I do not hear anything

![image](https://user-images.githubusercontent.com/68332732/88190263-5be31680-cc3a-11ea-99ab-d3cc25a0e134.png)

Anyway, I leave you in peace for now, you deserve a break from me and my problems. ^^

Thanks a lot again for all the help!

**Comment by casperiv0** [comment]
No problem, I'll close this issue here, If you find anything else feel free to open a new issue :)
