### ISSUE TITLE
LOADING BUG

### ISSUE THREAD

**Issue by dane-az** [Dev-CasperTheGhost/snaily-cadv2#29]
**Describe the bug**
Hey
SnailyCADv2 is installed without any Problems on the Server(No errors in Console) .
**To Reproduce**

When im trying to Login or even create a account, the Circle is just loading and nothing happends.

SCREEN:
https://prnt.sc/u6x3p0
https://prnt.sc/u6x4ng

Do you know how i can fix that?

**Comment by casperiv0** [comment]
Hi,

I see you have something else running on port 80, make sure to stop that resource, if it's something important scroll down on how to change the port for the `client`. You should also definitely update `npm` to the latest version (v12+). 

Make sure you have configured `client/src/config/config.js` correctly too.

### How to change port for the client 

1. goto the `client` folder
2. Open `package.json`
3. Find `serve` in `scripts` 
4. Change `80` to any port you'd like

Screenshot
![image](https://user-images.githubusercontent.com/53900565/91466452-7474cb00-e88f-11ea-8da5-52099c7c235e.png)

if you have any other problems, check the other issues created for a fix, If you don't find any fix for this issue, let me know.

Thankyou!

**Comment by dane-az** [comment]
Hey, 
How do i update NODE/NPM? 
Mine is working on 10.21.0 on Linux right now.
Port is changed to 94(works is still on 94) but the Problem is still there:


client/src/config/config.js
`export const backendURL = "http://localhost:3001" // this is the URL that calls the backend, please make sure this is a valid full URL (http(s)) and valid port`

MAIN/config.js
`module.exports = {
    host: "localhost",
    databaseUser: "snaily-cad",
    database: "snaily-cad",
    databasePassword: "********",
    env: "pre-alpha",
    port: "3001", // WARNING: If you change this port, make sure to edit the "proxy" in client/package.json
    jwt_secret: "secret"
}`

client/packages.json
`{
  "name": "client",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@material-ui/core": "^4.11.0",
    "@material-ui/lab": "^4.0.0-alpha.56",
    "@testing-library/jest-dom": "^5.11.2",
    "@testing-library/react": "^10.4.7",
    "@testing-library/user-event": "^12.1.0",
    "axios": "^0.19.2",
    "bootstrap": "^4.5.0",
    "js-cookie": "^2.2.1",
    "jwt-decode": "^2.2.0",
    "leaflet": "^1.6.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-leaflet": "^2.7.0",
    "react-markdown": "^4.3.1",
    "react-redux": "^7.2.1",
    "react-router-dom": "^5.2.0",
    "react-scripts": "3.4.1",
    "react-thunk": "^1.0.0",
    "reactstrap": "^8.5.1",
    "recharts": "^1.8.5",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0",
    "socket.io-client": "^2.3.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "jest --config ./jest.config.json",
    "eject": "react-scripts eject",
    "serve": "serve -s build -l 94"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
`

node -v: 
v10.21.0


How do i update node/npm?

Thanks for your help!

**Comment by dane-az** [comment]
So i updated node/npm to v14.9.0


But the problem is still the same

**Comment by casperiv0** [comment]
in `client/src/config/config.js` change `http://localhost:3001` to  `http://your-cad-url:3001`, E.G. `http://cool-rp-cad.com:3001` that should do it.

**Comment by ELITE-DANE** [comment]
Wont work, so i tried to different types of writeing it first:

https://
and 
http://

both wont work and the circle is still loading only when login in oder register account

Maybe we can do a discord call or something like this for a better troubleshooting

**Comment by ELITE-DANE** [comment]
Fact: By visiting the IP:3001 shows up "CANNOT GET /"
But when opening the site defined in "client/src/config/config.js" he shows up site not avalibile

**Comment by dane-az** [comment]
Works. 
Thanks!

**Comment by casperiv0** [comment]
Cool!
