### ISSUE TITLE
Language issue

### ISSUE THREAD

**Issue by dane-az** [Dev-CasperTheGhost/snaily-cadv2#30]
Hey, 
I changed the language file (client/src/language.json) and restarted the CAD but it wont work at all, its still the standard

**Comment by casperiv0** [comment]
Make sure to run `npm run build` in the client folder after making changes to `language.json`, that should fix your issue.

**Comment by dane-az** [comment]
THANKS!

**Comment by casperiv0** [comment]
No problem, feel free to close this issue. If you've got any other questions let me know.
