### ISSUE TITLE
PM2 Error

### ISSUE THREAD

**Issue by AZDPS** [Dev-CasperTheGhost/snaily-cadv2#31]
**Describe the bug**
I attempted to install and run PM2 as you mentioned in one of your previous bug reports, as follows:

- First: npm install -g pm2
- In server folder: pm2 start server.js --name cad-server
- In client folder: pm2 start npm --name cad-client -- run serve
- then run pm2 startup that should do the trick

I looked in the PM2 logs, because the server only starts if I manually type "npm start" in the snaily-cad folder, instead of automatically starting like it should with PM2. Here are the logs: [https://pastebin.com/gTdZdTPR](https://pastebin.com/gTdZdTPR)

**Expected behavior**
PM2 to auto-start the server/client as is when manually started with the command `npm start`

**Screenshots**
Screenshots: [https://imgur.com/a/WBBtAsH](https://imgur.com/a/WBBtAsH)

**Comment by casperiv0** [comment]
Hello,

Sorry I have not gotten back to you, this version of the CAD will be archived, If you'd like to use the new version of the CAD, [view it here](https://github.com/dev-caspertheghost/snaily-cadv3). v3 is currently still a work in progress with not too much left to do.

Thanks Casper.
