### ISSUE TITLE
Viewing Citizen returns no registered vehicles

### ISSUE THREAD

**Issue by Drew-Dodson** [Dev-CasperTheGhost/snaily-cadv2#33]
**Describe the bug**
When you view a citizen of yours that has registered vehicles it returns none and just has a loading logo

**To Reproduce**

http://demo-cad.caspertheghost.me/citizen/64 returns no vehicles. I have validated on my install the records are created in the DB

**Expected behavior**
Return all registered vehicles

**Screenshots**
![Capture](https://user-images.githubusercontent.com/8669465/94180752-59c45080-fe53-11ea-874b-0386329cf906.JPG)

**Additional context**
N/A

**Comment by casperiv0** [comment]
Hi, thanks for reporting. This is not a bug, looks more like a slow connection (server side) since I have a few other applications running on that VPS. Try hard refreshing the page (cmd/ctrl + shift + R). 

if you have any other issues feel free to open another issue.

**Comment by Drew-Dodson** [comment]
Hey, this issue also exists on my SnailyCAd instance on my physical box.

**Comment by casperiv0** [comment]
Their could be a bad connection on the server/VPS you're using.

**Comment by Drew-Dodson** [comment]
Bad connection to the DB or to the end-user?

**Comment by casperiv0** [comment]
It depends, If you have a slow speed on the VPS/hosting machine then it's just slow when the user connects to the server

**Comment by Drew-Dodson** [comment]
Well I don’t think it is that. It is a physical box I own with more than enough power. I am connected to it and then am running localhost as my address in the URL and it still doesn’t return. So on your demo If you connect to it and use localhost it returns vehicles?
