### ISSUE TITLE
SSL/TLS Support

### ISSUE THREAD

**Issue by Drew-Dodson** [Dev-CasperTheGhost/snaily-cadv2#34]
**Describe the feature you'd like**
Support for SSL/TLS with either self-signed certs generated with a tool like Java's keytool or a real certificate from Let's Encrypt

**Additional context**
N/A

**Comment by casperiv0** [comment]
Hi, 

You can currently do this using NGINX or Apache. There's not way of implementing it into the CAD/MDT directly.
