### ISSUE TITLE
LOADING BUG

### ISSUE THREAD

**Issue by Bastiti** [Dev-CasperTheGhost/snaily-cadv2#36]
While trying to register someone, there's is an infinite load.

**Comment by Bastiti** [comment]
Only while trying to access not via localhost

**Comment by Bastiti** [comment]
`export const backendURL = "http://192.168.1.176:3001" // this is the URL that calls the backend, please make sure this is a valid full URL (http(s)) and valid port`

**Comment by casperiv0** [comment]
Hi, 

Can you please check some of the other issues? A few other people had the same issue. 

Thanks

**Comment by Bastiti** [comment]
Saw the others issue. And nothing could works.

I've even openned port 3001 on my box. Nothing is working :/

**Comment by casperiv0** [comment]
Hello,

Sorry I have not gotten back to you, this version of the CAD will be archived, If you'd like to use the new version of the CAD, [view it here](https://github.com/dev-caspertheghost/snaily-cadv3). v3 is currently still a work in progress with not too much left to do.

Thanks Casper.
