### ISSUE TITLE
911 Integration Not Working

### ISSUE THREAD

**Issue by MiddleSkillz** [Dev-CasperTheGhost/snaily-cadv2#5]
**Describe the bug**
When you download the 911 integration it doesn't seem to work, I type the command and a report but it does not show up in the CAD

**To Reproduce**
1. Download 911 In Game Integration
2. Try to Use it
3. Nothing comes up in CAD

**Expected behavior**
For the call to show up in the CAD

**Screenshots**

**Additional context**

**Comment by casperiv0** [comment]
Hey! 

I'm sorry for the inconvenience, I might've not updated that script in a little bit, I'm currently stuck with a broken collarbone so I won't really be able to update that script for now. I'll keep you updated on progress on the script.

Thanks!

**Comment by MiddleSkillz** [comment]
Okay, no problem, get well, and then worry about it.

**Comment by casperiv0** [comment]
Thanks a lot!
