### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by RangerZL** [Dev-CasperTheGhost/snaily-cadv2#6]
**Describe the feature you'd like**
A clear and concise description of what you want to have as a new feature.
A sync with Wraith ARS 2X and The Cad
Notifications in game when bolo calls are made in the cad
A sound when attached to a call
A sound when theres a 911 caller
The ability to turn on register button and have admins only create the logins
Remove the top icons when at the login page but when logged in add them back
A syned ALPR system with Wraith ARS 2x and the Cad

**Comment by casperiv0** [comment]
Hey!

Thanks for sending these suggestions! I can already tell you some of these suggestions will be added soon :), such as the sounds.

Thanks, Casper.

**Comment by RangerZL** [comment]
Thanks 🙏

**Comment by casperiv0** [comment]
I've written all the suggestions down, closing issue.

Thanks again for the suggestions
