### ISSUE TITLE
Error when creating MySQL Database

### ISSUE THREAD

**Issue by andrewconleyaziti** [Dev-CasperTheGhost/snaily-cadv2#7]
**Describe the bug**
I am receiving an error when creating the database 'snaily-cad' in MySQL on Ubuntu 18.04 running on Amazon AWS.

mysql> CREATE DATABASE snaily-cad;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-cad' at line 1

**To Reproduce**
Steps to reproduce the behavior: N/A - attempting to create the DB in MySQL

**Expected behavior**
Expected behavior should be a normal OK response from the MySQL server.

**Screenshots**
N/A

**Comment by casperiv0** [comment]
hey!

try to name the database `snailycad` witthout the dash (-).

Thanks Casper

**Comment by andrewconleyaziti** [comment]
Casper, 
Just did that - now my server is not allowing me to register an account. I have an A record for my FQDN (cad.errdoj.com) pointing to the public IP of my AWS instance, so I used that in the /client/src/config/config.js where "localhost:3001" is now "cad.errdoj.com:3001" as is suggested in your FAQ section. Should this be my IPv4 address instead?

Here's the log from npm start:

[0] > npm start --prefix server
[0]
[1]
[1] > snailycad-v2@1.3.3 client /home/ubuntu/snaily-cadv2
[1] > npm run serve --prefix client
[1]
[1]
[1] > client@0.1.0 serve /home/ubuntu/snaily-cadv2/client
[1] > serve -s build -l 80
[1]
[0]
[0] > snailycad-server@1.0.0 start /home/ubuntu/snaily-cadv2/server
[0] > nodemon server.js
[0]
[0] [nodemon] 2.0.4
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching path(s): *.*
[0] [nodemon] watching extensions: js,mjs,json
[0] [nodemon] starting `node server.js`
[1] INFO: Accepting connections at http://localhost:80
[0] Connected to Database
[0]
[0] You're all up to date.

**Comment by casperiv0** [comment]
I think it's because the URL (`cad.errdoj.com`) is connected with port 80 and cannot change, the best thing todo if you don't want to use the IPv4 of the AWS server, you'll need to setup your apps with nginx, You can always try with the IPv4 of the AWS server.
PS: make sure if you change it to the IPv4 at `"proxy"` in `/client/package.json`

Make sure to run `npm run build` after updating `/client/src/config/config.js`

**Comment by andrewconleyaziti** [comment]
Tried both in the package.json and config.js - with both the public IPv4 and FQDN. Any thoughts on how I can get it to work properly? I tried using localhost as well, but that still didn't work as I wanted it to. How'd you setup your demo CAD? Did you just leave everything as default?

**Comment by casperiv0** [comment]
My demo CAD is set up with nginx, It's hosted on a VPS on port 3001 and 3002, but with nginx you can change that to an URL and subdomain. You can follow along [this GitHub gist](https://gist.github.com/bradtraversy/cd90d1ed3c462fe3bddd11bf8953a896) It's very helpful. If that wouldn't help, I can always send you the config files for your server configuration.

**Comment by andrewconleyaziti** [comment]
What OS did you use on your VPS? I'm trying it on Ubuntu 16.04 LTS.

**Comment by andrewconleyaziti** [comment]
Got this error when attempting to run the `npm run create` command on Ubuntu 16.04LTS running Node v12.18.1

[https://i.gyazo.com/e1be95f5a0592501d5c3912f9caf87d2.png](url)

**Comment by casperiv0** [comment]
you need to use `sudo npm create` It's [bcrypt](https://www.npmjs.com/package/bcrypt) that needs admin permissions.

**Comment by andrewconleyaziti** [comment]
Hm, I just tried that and got the same error. Let me just try re-installing everything again using sudo.

**Comment by casperiv0** [comment]
If that doesn't work, try to manually installing bcrypt: `sudo npm install bcrypt` in the server folder.

**Comment by andrewconleyaziti** [comment]
Even after running 'sudo npm install bcrypt' on 18.04 (updated to Ubuntu 18.04 LTS) and then running 'sudo npm create' it comes up with this: [https://i.gyazo.com/359d3d2d0d63f0bd6f8e815283ae890e.png](url)

**Comment by casperiv0** [comment]
You should already have it installed now, to double check run `npm install` in the client folder and then follow the rest of the steps.

**Comment by andrewconleyaziti** [comment]
Got through that hurdle - now wonderful yarn has an issue when running `yarn global add serve` - No such file or directory: 'global'

**Comment by casperiv0** [comment]
make sure that you have the latest version of yarn installed, `sudo npm install -g yarn`, then run that in the client folder.

**Comment by andrewconleyaziti** [comment]
Tried that earlier, didn't work.

**Comment by andrewconleyaziti** [comment]
Got it, had to remove yarn and reinstall.

**Comment by casperiv0** [comment]
Alright

**Comment by andrewconleyaziti** [comment]
The only thing now is an error when running `npm start` in the server folder, 'Client does not support authentication protocol requested by server; consider upgrading MySQL client' - I used `sudo apt-get install mysql-server` to install MySQL, running version 5.7

**Comment by andrewconleyaziti** [comment]
Got it figured out.. Now onto nginx, which I was having trouble with the other day.

**Comment by casperiv0** [comment]
Alright, for nginx you can use this for help: https://gist.github.com/bradtraversy/cd90d1ed3c462fe3bddd11bf8953a896, he also has a video explaining it here might be a little more helpful: https://www.youtube.com/watch?v=oykl1Ih9pMg

**Comment by andrewconleyaziti** [comment]
Thanks for all your help! Appreciate it.

**Comment by casperiv0** [comment]
No problem.
